global:
  scrape_interval: 15s  # Intervalo de scraping, o padrão é 15 segundos

scrape_configs:
  # Scrape configuration for Eureka Server
  - job_name: 'eureka-server'
    metrics_path: /actuator/prometheus  # Adicionando o caminho de métricas
    static_configs:
      - targets: ['eureka:8761']

  # Scrape configuration for API Gateway
  - job_name: 'gateway'
    metrics_path: /actuator/prometheus  # Adicionando o caminho de métricas
    static_configs:
      - targets: ['gateway:9999']

  # Scrape configuration for Prometheus (auto-monitoring)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']